Repository NVIDIA/cuopt, pull requests merged in 2025-06, with the labels that each got.

#61 allow long client version in service version check'
  python/cuopt_server/cuopt_server/utils/job_queue.py
Labels: bug, non-breaking

#52 Fix obj constant on max. Fix undefined memory access at root
  cpp/src/dual_simplex/branch_and_bound.cpp
  cpp/src/linear_programming/utilities/logger_init.hpp
  cpp/src/mip/presolve/trivial_presolve.cuh
Labels: bug, non-breaking

#66 Write out mps file containing user problem. Useful for debugging
  cpp/include/cuopt/linear_programming/constants.h
  cpp/include/cuopt/linear_programming/mip/solver_settings.hpp
  cpp/include/cuopt/linear_programming/pdlp/solver_settings.hpp
  cpp/src/linear_programming/solve.cu
  cpp/src/math_optimization/solver_settings.cu
  cpp/src/mip/problem/write_mps.cu
  cpp/src/mip/solve.cu
  cpp/tests/mip/doc_example_test.cu
  docs/cuopt/source/cuopt-c/lp-milp/lp-milp-c-api.rst
  docs/cuopt/source/lp-milp-settings.rst
  python/cuopt/cuopt/linear_programming/solver/solver_parameters.pyx
  python/cuopt/cuopt/tests/linear_programming/test_lp_solver.py
Labels: non-breaking, improvement

#72 Enable nightly package publishing and fix nightly testing workflow
  .github/workflows/build.yaml
  .github/workflows/nightly.yaml
Labels: non-breaking, improvement

#73 Update PR template to be concise with checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: doc, non-breaking

#77 Documentation update to add third party modeling languages and nightly documentation
  README.md
  docs/cuopt/source/cuopt-python/quick-start.rst
  docs/cuopt/source/cuopt-server/quick-start.rst
  docs/cuopt/source/index.rst
  docs/cuopt/source/introduction.rst
  docs/cuopt/source/lp-features.rst
  docs/cuopt/source/lp-milp-settings.rst
  docs/cuopt/source/milp-features.rst
  docs/cuopt/source/thirdparty_modeling_languages/index.rst
Labels: doc, non-breaking

#79 Branch 25.08 merge 25.05
  .github/workflows/build.yaml
  .github/workflows/nightly.yaml
  README.md
  cpp/include/cuopt/linear_programming/constants.h
  cpp/include/cuopt/linear_programming/mip/solver_settings.hpp
  cpp/include/cuopt/linear_programming/pdlp/solver_settings.hpp
  cpp/include/cuopt/linear_programming/utilities/cython_solve.hpp
  cpp/src/dual_simplex/branch_and_bound.cpp
  cpp/src/linear_programming/solve.cu
  cpp/src/linear_programming/utilities/cython_solve.cu
  cpp/src/linear_programming/utilities/logger_init.hpp
  cpp/src/math_optimization/solver_settings.cu
  cpp/src/mip/presolve/trivial_presolve.cuh
  cpp/src/mip/problem/write_mps.cu
  cpp/src/mip/solve.cu
  cpp/tests/mip/doc_example_test.cu
  docs/cuopt/source/cuopt-c/lp-milp/lp-milp-c-api.rst
  docs/cuopt/source/cuopt-python/quick-start.rst
  docs/cuopt/source/cuopt-server/quick-start.rst
  docs/cuopt/source/index.rst
  docs/cuopt/source/introduction.rst
  docs/cuopt/source/lp-features.rst
  docs/cuopt/source/lp-milp-settings.rst
  docs/cuopt/source/milp-features.rst
  docs/cuopt/source/thirdparty_modeling_languages/index.rst
  python/cuopt/cuopt/linear_programming/solver/solver_parameters.pyx
  python/cuopt/cuopt/tests/linear_programming/test_lp_solver.py
  python/cuopt_server/cuopt_server/utils/job_queue.py
Labels: non-breaking, improvement

#78 Fix nightly build which is failing on jq request
  .github/workflows/nightly.yaml
  .github/workflows/test.yaml
Labels: bug, non-breaking

#80 Migrate to modern logger interface
  python/cuopt_self_hosted/cuopt_sh_client/cuopt_self_host_client.py
  python/cuopt_server/cuopt_server/cuopt_service.py
  python/cuopt_server/cuopt_server/utils/job_queue.py
Labels: non-breaking, improvement

#82 Fix inversion of constraint bounds in conditional bounds presolve
  cpp/include/cuopt/linear_programming/mip/solver_settings.hpp
  cpp/src/mip/diversity/diversity_manager.cu
  cpp/src/mip/presolve/bounds_presolve.cu
  cpp/src/mip/presolve/bounds_update_helpers.cuh
  cpp/src/mip/problem/problem.cu
  cpp/src/mip/problem/problem_helpers.cuh
Labels: bug, non-breaking

#62 Update Source build instructions
  CONTRIBUTING.md
Labels: doc, non-breaking

#83 Fix occasional incorrect solution bound on maximization problems
  cpp/src/mip/diversity/diversity_manager.cu
  cpp/tests/mip/termination_test.cu
  cpp/tests/mip/unit_test.cu
  datasets/mip/cod105_max.mps
  docs/cuopt/source/release-notes.rst
  python/cuopt_server/cuopt_server/tests/test_lp.py
Labels: bug, non-breaking

#88 Fix test commands in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: doc, non-breaking

#95 Branch 25.08 merge branch 25.05
  .github/workflows/nightly.yaml
  .github/workflows/test.yaml
  CONTRIBUTING.md
  README.md
  cpp/src/mip/diversity/diversity_manager.cu
  cpp/src/mip/presolve/bounds_presolve.cu
  cpp/src/mip/problem/problem.cu
  cpp/tests/mip/termination_test.cu
  cpp/tests/mip/unit_test.cu
  datasets/mip/cod105_max.mps
  docs/cuopt/source/release-notes.rst
  python/cuopt_self_hosted/cuopt_sh_client/cuopt_self_host_client.py
  python/cuopt_server/cuopt_server/cuopt_service.py
  python/cuopt_server/cuopt_server/tests/test_lp.py
  python/cuopt_server/cuopt_server/utils/job_queue.py
Labels: non-breaking, improvement

#105 Fix crash on models with variables but no constraints
  cpp/src/mip/problem/problem.cu
  cpp/src/mip/problem/problem_helpers.cuh
  cpp/src/mip/solve.cu
  cpp/tests/mip/empty_fixed_problems_test.cu
  cpp/tests/mip/termination_test.cu
  datasets/mip/empty-max-problem-objective-vars.mps
  datasets/mip/empty-problem-objective-vars.mps
  datasets/mip/trivial-presolve-no-obj-vars.mps
Labels: bug, non-breaking

#110 Fix batch graph capture issue caused by pinned memory allocator
  cpp/src/linear_programming/step_size_strategy/adaptive_step_size_strategy.cu
  cpp/src/linear_programming/step_size_strategy/adaptive_step_size_strategy.hpp
  cpp/src/linear_programming/utilities/cython_solve.cu
  cpp/src/utilities/unique_pinned_ptr.hpp
Labels: bug, non-breaking, pdlp

#99 refactor(shellcheck): fix all remaining shellcheck errors/warnings
  .pre-commit-config.yaml
  build.sh
  datasets/get_test_data.sh
  datasets/linear_programming/download_pdlp_test_dataset.sh
  datasets/mip/download_miplib_test_dataset.sh
  datasets/mip/presolve_instance.sh
  print_env.sh
  python/libcuopt/libcuopt/tests/test_cli.sh
Labels: non-breaking, improvement

#125 Relax pinnings on several dependencies, remove nvidia channel
  README.md
  conda/environments/all_cuda-128_arch-aarch64.yaml
  conda/environments/all_cuda-128_arch-x86_64.yaml
  conda/recipes/cuopt/recipe.yaml
  dependencies.yaml
  docs/cuopt/source/cuopt-c/quick-start.rst
  docs/cuopt/source/cuopt-python/quick-start.rst
  docs/cuopt/source/cuopt-server/quick-start.rst
  python/cuopt/pyproject.toml
  python/cuopt_server/pyproject.toml
  python/libcuopt/libcuopt/tests/test_cli.sh
Labels: non-breaking, improvement

#127 refactor(rattler): remove cuda11 options and general cleanup
  conda/recipes/cuopt/conda_build_config.yaml
  conda/recipes/cuopt/recipe.yaml
  conda/recipes/libcuopt/conda_build_config.yaml
  conda/recipes/libcuopt/recipe.yaml
Labels: non-breaking, improvement

#126 use 25.08 versions of RAPIDS CI workflows
  .github/workflows/build.yaml
Labels: non-breaking, improvement

#130 Small fixes for corner cases:
  cpp/src/mip/problem/load_balanced_problem.cu
  cpp/src/mip/problem/problem.cu
Labels: non-breaking, improvement

#118 Fix the link to Python docs in README
  README.md
Labels: doc, non-breaking

#129 Small improvements on how paths are handled in tests
  cpp/tests/mip/doc_example_test.cu
  cpp/tests/mip/feasibility_jump_tests.cu
Labels: non-breaking, improvement
