Repository NVIDIA/cuopt, pull requests merged in 2025-07, with the labels that each got.

#175 Fix versioning for nightly and release package
  ci/build_wheel.sh
Labels: breaking, improvement

#131 Fix incorrect reported solving time
  cpp/src/mip/diversity/diversity_manager.cu
  cpp/src/utilities/scope_guard.hpp
  cpp/tests/linear_programming/c_api_tests/c_api_tests.cpp
Labels: bug, non-breaking

#149 Fix several bugs appeared in unit testing of JuMP interface
  cpp/include/cuopt/linear_programming/cuopt_c.h
  cpp/include/cuopt/linear_programming/pdlp/solver_solution.hpp
  cpp/src/dual_simplex/solve.cpp
  cpp/src/linear_programming/cuopt_c.cpp
  cpp/src/linear_programming/solver_solution.cu
  cpp/src/linear_programming/termination_strategy/convergence_information.cu
  cpp/src/math_optimization/solver_settings.cu
  cpp/src/mip/presolve/trivial_presolve.cuh
  cpp/src/mip/problem/problem.cu
  cpp/src/mip/problem/problem.cuh
  cpp/src/mip/problem/problem_helpers.cuh
  cpp/src/mip/solution/solution.cu
  cpp/src/mip/solve.cu
  cpp/src/mip/solver.cu
  cpp/src/utilities/cuda_helpers.cuh
  cpp/tests/linear_programming/pdlp_test.cu
  cpp/tests/linear_programming/utilities/pdlp_test_utilities.cuh
  cpp/tests/mip/CMakeLists.txt
  cpp/tests/mip/empty_fixed_problems_test.cu
  cpp/tests/mip/integer_with_real_bounds.cu
  cpp/tests/mip/mip_utils.cuh
  cpp/tests/mip/miplib_test.cu
  cpp/tests/mip/problem_test.cu
  cpp/tests/mip/termination_test.cu
  datasets/linear_programming/lp-model-no-constraints.mps
  datasets/mip/integer-with-real-bounds.mps
Labels: bug, non-breaking

#191 Fix bug in scaling of dual slacks and sign of dual variables for >= constraints
  cpp/src/dual_simplex/presolve.cpp
  cpp/src/dual_simplex/presolve.hpp
  cpp/src/dual_simplex/scaling.cpp
  cpp/src/dual_simplex/solve.cpp
  cpp/tests/dual_simplex/unit_tests/solve.cpp
Labels: bug, non-breaking

#201 Fix logging levels
  cpp/CMakeLists.txt
  cpp/src/linear_programming/utilities/logger_init.hpp
Labels: bug, non-breaking

#215 Disable feasibility jump test for one of the dataset
  cpp/tests/mip/feasibility_jump_tests.cu
Labels: bug, non-breaking

#213 Adding few more pre-commit checks to ensure coding standards
  .clang-format
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/nightly.yaml
  .github/workflows/service_nightly.yaml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  benchmarks/linear_programming/utils/get_datasets.py
  conda/README.md
  cpp/CMakeLists.txt
  cpp/README.md
  cpp/cmake/thirdparty/cccl_override.json
  cpp/docs/DEVELOPER_GUIDE.md
  cpp/doxygen/Doxyfile
  cpp/src/math_optimization/CMakeLists.txt
  cpp/src/mip/CMakeLists.txt
  cpp/src/routing/CMakeLists.txt
  cpp/tests/CMakeLists.txt
  cpp/tests/examples/CMakeLists.txt
  cpp/tests/examples/routing/CMakeLists.txt
  cpp/tests/examples/routing/README.md
  cpp/tests/mip/CMakeLists.txt
  cpp/tests/utilities/CMakeLists.txt
  datasets/mip/sudoku.mps
  docs/cuopt/README.md
  docs/cuopt/source/conf.py
  docs/cuopt/source/cuopt-c/lp-milp/lp-example.rst
  docs/cuopt/source/cuopt-c/lp-milp/milp-examples.rst
  docs/cuopt/source/cuopt-cli/cli-examples.rst
  docs/cuopt/source/cuopt-server/client-api/sh-cli-build.rst
  docs/cuopt/source/cuopt-server/csp-guides/index.rst
  docs/cuopt/source/cuopt-server/examples/index.rst
  docs/cuopt/source/cuopt-server/examples/lp-examples.rst
  docs/cuopt/source/cuopt-server/examples/milp-examples.rst
  docs/cuopt/source/cuopt-server/examples/routing-examples.rst
  docs/cuopt/source/cuopt-server/index.rst
  docs/cuopt/source/faq.rst
  docs/cuopt/source/hidden/limitations.rst
  docs/cuopt/source/index.rst
  docs/cuopt/source/introduction.rst
  docs/cuopt/source/lp-features.rst
  docs/cuopt/source/milp-features.rst
  docs/cuopt/source/project.json
  docs/cuopt/source/release-notes.rst
  docs/cuopt/source/routing-features.rst
  docs/cuopt/source/versions1.json
  python/cuopt/CMakeLists.txt
  python/cuopt/cuopt/routing/structure/routing_utilities.pxd
  python/cuopt_self_hosted/README.md
  python/cuopt_server/cuopt_server/cuopt_service.py
  python/cuopt_server/cuopt_server/utils/job_queue.py
Labels: doc, non-breaking

#114 cuopt service add healthcheck for /
  python/cuopt_server/cuopt_server/tests/test_cuopt_amr_service.py
  python/cuopt_server/cuopt_server/webserver.py
Labels: non-breaking, improvement

#87 Create a bash script to run mps files in parallel
  benchmarks/linear_programming/run_mps_files.sh
Labels: non-breaking, improvement

#203 Enable doc build workflow and build script for PR and Nightly
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  ci/build_docs.sh
  ci/release/update-version-rapids.sh
  conda/recipes/cuopt-server/recipe.yaml
  conda/recipes/cuopt-sh-client/recipe.yaml
  dependencies.yaml
Labels: doc, non-breaking

#120 Use cusparsespmv_preprocess() now that Raft implements it.
  cpp/src/linear_programming/cusparse_view.hpp
Labels: non-breaking, improvement, pdlp

#225 No cuda graph in batched pdlp
  cpp/include/cuopt/linear_programming/solve.hpp
  cpp/include/cuopt/linear_programming/utilities/cython_solve.hpp
  cpp/src/linear_programming/pdhg.cu
  cpp/src/linear_programming/pdhg.hpp
  cpp/src/linear_programming/pdlp.cu
  cpp/src/linear_programming/pdlp.cuh
  cpp/src/linear_programming/restart_strategy/pdlp_restart_strategy.cu
  cpp/src/linear_programming/restart_strategy/pdlp_restart_strategy.cuh
  cpp/src/linear_programming/restart_strategy/weighted_average_solution.cu
  cpp/src/linear_programming/restart_strategy/weighted_average_solution.hpp
  cpp/src/linear_programming/solve.cu
  cpp/src/linear_programming/step_size_strategy/adaptive_step_size_strategy.cu
  cpp/src/linear_programming/step_size_strategy/adaptive_step_size_strategy.hpp
  cpp/src/linear_programming/utilities/cython_solve.cu
  cpp/src/linear_programming/utilities/ping_pong_graph.cuh
  python/cuopt/cuopt/tests/linear_programming/test_lp_solver.py
Labels: bug, non-breaking, pdlp

#74 Fix data initialization in create depot node for max travel time feature
  cpp/src/routing/adapters/assignment_adapter.cuh
  cpp/src/routing/solution/solution.cuh
  cpp/tests/routing/CMakeLists.txt
  cpp/tests/routing/l2_routing_test.cu
  cpp/tests/routing/level1/l1_cycle_finder.cu
  cpp/tests/routing/utilities/mg_utilities.hpp
Labels: bug, non-breaking

#226 Fix bug on initial solution size in the check and cuda set device order
  cpp/src/linear_programming/utilities/problem_checking.cu
  cpp/src/mip/diversity/diversity_manager.cu
  cpp/src/mip/utils.cuh
  cpp/tests/mip/CMakeLists.txt
Labels: bug, non-breaking

#58 Add CTK 12.9 fatbin flags to maintain existing binary sizes
  cpp/CMakeLists.txt
Labels: non-breaking, improvement

#230 Bump actions/checkout in nightly.yaml to v4
  .github/workflows/nightly.yaml
Labels: non-breaking, improvement

#224 Add helm chart for cuopt service
  .pre-commit-config.yaml
  ci/release/update-version-cuopt.sh
  helmchart/cuopt-server/Chart.yaml
  helmchart/cuopt-server/README.md
  helmchart/cuopt-server/templates/NOTES.txt
  helmchart/cuopt-server/templates/_helpers.tpl
  helmchart/cuopt-server/templates/deployment.yaml
  helmchart/cuopt-server/templates/ingress.yaml
  helmchart/cuopt-server/templates/service.yaml
  helmchart/cuopt-server/templates/serviceaccount.yaml
  helmchart/cuopt-server/values.yaml
Labels: non-breaking, improvement

#180 Add nightly container support
  .github/workflows/build.yaml
  .github/workflows/build_images.yaml
  .github/workflows/build_test_publish_images.yaml
  .github/workflows/service_nightly.yaml
  .github/workflows/test_images.yaml
  ci/docker/Dockerfile
  ci/docker/README.md
  ci/docker/context/README.md
  ci/docker/create_multiarch_manifest.sh
  ci/docker/test_image.sh
  python/cuopt_server/cuopt_server/tests/utils/utils.py
Labels: non-breaking, improvement

#200 Fix: various typos in comments and strings, note on result dir
  python/cuopt_self_hosted/cuopt_sh_client/thin_client_solver_settings.py
  python/cuopt_server/cuopt_server/utils/job_queue.py
  python/cuopt_server/cuopt_server/webserver.py
Labels: non-breaking, improvement

#229 Add link checker for doc build and test
  build.sh
  docs/cuopt/Makefile
  docs/cuopt/source/conf.py
  docs/cuopt/source/cuopt-c/lp-milp/lp-example.rst
  docs/cuopt/source/cuopt-c/lp-milp/lp-milp-c-api.rst
  docs/cuopt/source/cuopt-c/lp-milp/milp-examples.rst
  docs/cuopt/source/cuopt-cli/quick-start.rst
  docs/cuopt/source/cuopt-python/quick-start.rst
  docs/cuopt/source/cuopt-server/client-api/sh-cli-build.rst
  docs/cuopt/source/cuopt-server/csp-guides/csp-aws.rst
  docs/cuopt/source/cuopt-server/csp-guides/csp-azure.rst
  docs/cuopt/source/cuopt-server/examples/lp-examples.rst
  docs/cuopt/source/cuopt-server/examples/milp-examples.rst
  docs/cuopt/source/cuopt-server/examples/routing-examples.rst
  docs/cuopt/source/cuopt-server/quick-start.rst
  docs/cuopt/source/faq.rst
  docs/cuopt/source/introduction.rst
  docs/cuopt/source/lp-features.rst
  docs/cuopt/source/lp-milp-settings.rst
  docs/cuopt/source/milp-features.rst
  docs/cuopt/source/routing-features.rst
Labels: doc, non-breaking

#222 Remove cuda 11 specific changes from repo
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  build.sh
  cpp/CMakeLists.txt
  cpp/src/linear_programming/utilities/ping_pong_graph.cuh
  cpp/src/mip/feasibility_jump/feasibility_jump.cu
  cpp/src/mip/presolve/load_balanced_bounds_presolve.cu
  cpp/src/routing/cuda_graph.cuh
Labels: non-breaking, improvement

#248 Unset NDEBUG in cmake in assert mode
  cpp/CMakeLists.txt
  cpp/src/mip/diversity/assignment_hash_map.cu
  cpp/src/mip/solution/solution.cu
  cpp/src/utilities/macros.cuh
  cpp/tests/mip/bounds_standardization_test.cu
  cpp/tests/mip/elim_var_remap_test.cu
Labels: bug, non-breaking

#235 Fix assert failure on MIP problem reducing to LP after presolve
  cpp/src/linear_programming/solve.cu
  cpp/src/linear_programming/solve.cuh
  cpp/src/mip/solve.cu
  cpp/src/mip/solver.cu
  cpp/tests/mip/empty_fixed_problems_test.cu
  datasets/mip/mip-presolved-to-lp.mps
Labels: bug, non-breaking

#242 Manual cuda graph creation in load balanced bounds presolve
  cpp/src/mip/presolve/bounds_presolve.cu
  cpp/src/mip/presolve/bounds_presolve.cuh
  cpp/src/mip/presolve/load_balanced_bounds_presolve.cu
  cpp/src/mip/presolve/load_balanced_bounds_presolve.cuh
  cpp/src/mip/presolve/load_balanced_bounds_presolve_helpers.cuh
  cpp/src/mip/presolve/load_balanced_bounds_presolve_kernels.cuh
  cpp/tests/mip/CMakeLists.txt
  cpp/tests/mip/load_balancing_test.cu
Labels: bug, non-breaking
