Repository NVIDIA/cuopt, pull requests merged in 2025-09, with the labels that each got.

#362 Add Commit Sha to container for reference
  .github/workflows/build_images.yaml
  .github/workflows/build_test_publish_images.yaml
  .github/workflows/test_images.yaml
  ci/docker/Dockerfile
  python/cuopt_server/cuopt_server/utils/utils.py
Labels: non-breaking, improvement

#352 QPS extension for MPS
  .gitattributes
  .gitignore
  cpp/libmps_parser/include/mps_parser/data_model_view.hpp
  cpp/libmps_parser/include/mps_parser/mps_data_model.hpp
  cpp/libmps_parser/include/mps_parser/parser.hpp
  cpp/libmps_parser/src/data_model_view.cpp
  cpp/libmps_parser/src/mps_data_model.cpp
  cpp/libmps_parser/src/mps_parser.cpp
  cpp/libmps_parser/src/mps_parser.hpp
  cpp/libmps_parser/tests/mps_parser_test.cpp
  datasets/quadratic_programming/QP_Test_1.qps
  datasets/quadratic_programming/QP_Test_2.qps
Labels: feature request, non-breaking

#357 Decompression for .mps.gz and .mps.bz2 files
  ci/build_wheel_cuopt_mps_parser.sh
  conda/environments/all_cuda-129_arch-aarch64.yaml
  conda/environments/all_cuda-129_arch-x86_64.yaml
  conda/recipes/libcuopt/recipe.yaml
  conda/recipes/mps-parser/recipe.yaml
  cpp/libmps_parser/CMakeLists.txt
  cpp/libmps_parser/include/mps_parser/parser.hpp
  cpp/libmps_parser/src/mps_parser.cpp
  cpp/libmps_parser/src/mps_parser.hpp
  cpp/libmps_parser/src/utilities/error.hpp
  cpp/libmps_parser/tests/mps_parser_test.cpp
  datasets/linear_programming/good-mps-1.mps.bz2
  datasets/linear_programming/good-mps-1.mps.gz
  dependencies.yaml
  thirdparty/THIRD_PARTY_LICENSES
Labels: non-breaking, improvement

#375 Warn in case a dependent library is not found in libcuopt load
  python/libcuopt/libcuopt/load.py
Labels: non-breaking, improvement

#370 Print cuOpt version / machine info before solving
  cpp/CMakeLists.txt
  cpp/src/CMakeLists.txt
  cpp/src/linear_programming/solve.cu
  cpp/src/mip/solve.cu
  cpp/src/utilities/version_info.cpp
  cpp/src/utilities/version_info.hpp
Labels: non-breaking, improvement

#371 Enable parallelism for root node presolve
  ci/build_wheel_libcuopt.sh
  ci/utils/install_boost_tbb.sh
  conda/environments/all_cuda-129_arch-aarch64.yaml
  conda/environments/all_cuda-129_arch-x86_64.yaml
  conda/recipes/libcuopt/recipe.yaml
  cpp/CMakeLists.txt
  cpp/cmake/thirdparty/FindTBB.cmake
  cpp/src/mip/presolve/third_party_presolve.cpp
  cpp/src/mip/presolve/third_party_presolve.hpp
  cpp/src/mip/solve.cu
  dependencies.yaml
  python/libcuopt/CMakeLists.txt
Labels: non-breaking, improvement

#379 Add support for cuda13 container and fix cuda13 lib issues in wheel
  .github/workflows/build_test_publish_images.yaml
  README.md
  ci/docker/Dockerfile
  dependencies.yaml
  docs/cuopt/source/cuopt-c/quick-start.rst
  docs/cuopt/source/cuopt-python/quick-start.rst
  docs/cuopt/source/cuopt-server/quick-start.rst
  python/libcuopt/CMakeLists.txt
Labels: bug, non-breaking

#372 Combined variable bounds
  cpp/src/linear_programming/initial_scaling_strategy/initial_scaling.cu
  cpp/src/linear_programming/pdhg.cu
  cpp/src/linear_programming/pdlp.cu
  cpp/src/linear_programming/restart_strategy/pdlp_restart_strategy.cu
  cpp/src/linear_programming/termination_strategy/convergence_information.cu
  cpp/src/linear_programming/termination_strategy/infeasibility_information.cu
  cpp/src/linear_programming/translate.hpp
  cpp/src/linear_programming/utilities/problem_checking.cu
  cpp/src/linear_programming/utils.cuh
  cpp/src/mip/CMakeLists.txt
  cpp/src/mip/diversity/assignment_hash_map.cu
  cpp/src/mip/diversity/diversity_manager.cu
  cpp/src/mip/diversity/recombiners/bound_prop_recombiner.cuh
  cpp/src/mip/feasibility_jump/feasibility_jump.cu
  cpp/src/mip/feasibility_jump/feasibility_jump_kernels.cu
  cpp/src/mip/feasibility_jump/load_balancing.cuh
  cpp/src/mip/local_search/feasibility_pump/feasibility_pump.cu
  cpp/src/mip/local_search/feasibility_pump/feasibility_pump.cuh
  cpp/src/mip/local_search/local_search.cu
  cpp/src/mip/local_search/local_search.cuh
  cpp/src/mip/local_search/rounding/bounds_repair.cu
  cpp/src/mip/local_search/rounding/bounds_repair.cuh
  cpp/src/mip/local_search/rounding/constraint_prop.cu
  cpp/src/mip/local_search/rounding/constraint_prop.cuh
  cpp/src/mip/local_search/rounding/simple_rounding_kernels.cuh
  cpp/src/mip/presolve/bounds_presolve.cu
  cpp/src/mip/presolve/bounds_presolve.cuh
  cpp/src/mip/presolve/conditional_bound_strengthening.cu
  cpp/src/mip/presolve/lb_probing_cache.cu
  cpp/src/mip/presolve/load_balanced_partition_helpers.cuh
  cpp/src/mip/presolve/multi_probe.cu
  cpp/src/mip/presolve/multi_probe.cuh
  cpp/src/mip/presolve/probing_cache.cu
  cpp/src/mip/presolve/probing_cache.cuh
  cpp/src/mip/presolve/trivial_presolve.cuh
  cpp/src/mip/presolve/trivial_presolve_helpers.cuh
  cpp/src/mip/problem/host_helper.cuh
  cpp/src/mip/problem/problem.cu
  cpp/src/mip/problem/problem.cuh
  cpp/src/mip/problem/problem_helpers.cuh
  cpp/src/mip/problem/write_mps.cu
  cpp/src/mip/solution/feasibility_test.cuh
  cpp/src/mip/solution/solution.cu
  cpp/src/mip/solve.cu
  cpp/src/mip/utils.cuh
  cpp/src/utilities/copy_helpers.hpp
  cpp/tests/mip/CMakeLists.txt
  cpp/tests/mip/elim_var_remap_test.cu
  cpp/tests/mip/load_balancing_test.cu
  cpp/tests/mip/multi_probe_test.cu
Labels: non-breaking, improvement, mip

#368 Implement node presolve
  benchmarks/linear_programming/run_mps_files.sh
  cpp/src/dual_simplex/branch_and_bound.cpp
  cpp/src/dual_simplex/mip_node.hpp
  cpp/src/dual_simplex/phase2.hpp
  cpp/src/dual_simplex/presolve.cpp
  cpp/src/dual_simplex/presolve.hpp
Labels: non-breaking, improvement

#398 Remove limiting_resource_adaptor leftover
  benchmarks/linear_programming/cuopt/run_mip.cpp
Labels: bug, non-breaking

#382 Heuristic Improvements: balance between generation and improvement heuristics
  benchmarks/linear_programming/cuopt/mip_test_instances.hpp
  benchmarks/linear_programming/cuopt/run_mip.cpp
  cpp/include/cuopt/linear_programming/mip/solver_settings.hpp
  cpp/include/cuopt/logger.hpp
  cpp/src/dual_simplex/bound_flipping_ratio_test.cpp
  cpp/src/dual_simplex/branch_and_bound.cpp
  cpp/src/dual_simplex/phase2.cpp
  cpp/src/dual_simplex/presolve.cpp
  cpp/src/dual_simplex/simplex_solver_settings.hpp
  cpp/src/linear_programming/initial_scaling_strategy/initial_scaling.cu
  cpp/src/linear_programming/initial_scaling_strategy/initial_scaling.cuh
  cpp/src/linear_programming/pdlp.cu
  cpp/src/linear_programming/utilities/logger_init.hpp
  cpp/src/mip/diversity/assignment_hash_map.cu
  cpp/src/mip/diversity/diversity_config.hpp
  cpp/src/mip/diversity/diversity_manager.cu
  cpp/src/mip/diversity/diversity_manager.cuh
  cpp/src/mip/diversity/population.cu
  cpp/src/mip/diversity/population.cuh
  cpp/src/mip/diversity/recombiners/fp_recombiner.cuh
  cpp/src/mip/diversity/recombiners/recombiner.cuh
  cpp/src/mip/diversity/recombiners/recombiner_stats.hpp
  cpp/src/mip/diversity/recombiners/sub_mip.cuh
  cpp/src/mip/feasibility_jump/feasibility_jump.cu
  cpp/src/mip/feasibility_jump/feasibility_jump.cuh
  cpp/src/mip/local_search/feasibility_pump/feasibility_pump.cu
  cpp/src/mip/local_search/feasibility_pump/feasibility_pump.cuh
  cpp/src/mip/local_search/local_search.cu
  cpp/src/mip/local_search/local_search.cuh
  cpp/src/mip/local_search/rounding/constraint_prop.cu
  cpp/src/mip/local_search/rounding/constraint_prop.cuh
  cpp/src/mip/presolve/load_balanced_bounds_presolve_helpers.cuh
  cpp/src/mip/presolve/probing_cache.cu
  cpp/src/mip/presolve/trivial_presolve.cuh
  cpp/src/mip/problem/problem.cu
  cpp/src/mip/relaxed_lp/lp_state.cuh
  cpp/src/mip/relaxed_lp/relaxed_lp.cu
  cpp/src/mip/relaxed_lp/relaxed_lp.cuh
  cpp/src/mip/solve.cu
  cpp/src/mip/solver.cu
  cpp/tests/mip/bounds_standardization_test.cu
  cpp/tests/mip/elim_var_remap_test.cu
  cpp/tests/mip/load_balancing_test.cu
  cpp/tests/mip/multi_probe_test.cu
  docs/cuopt/source/lp-milp-settings.rst
Labels: non-breaking, improvement

#408 avoid triggering nightly tests until builds are complete
  .github/workflows/build.yaml
  .github/workflows/nightly.yaml
  .github/workflows/test_images.yaml
  docs/cuopt/source/cuopt-server/quick-start.rst
  docs/cuopt/source/faq.rst
Labels: non-breaking, improvement

#413 cuopt-server: update dependencies (drop httpx, add psutil)
  conda/environments/all_cuda-129_arch-aarch64.yaml
  conda/environments/all_cuda-129_arch-x86_64.yaml
  conda/environments/all_cuda-130_arch-aarch64.yaml
  conda/environments/all_cuda-130_arch-x86_64.yaml
  conda/recipes/cuopt-server/recipe.yaml
  dependencies.yaml
  python/cuopt_server/pyproject.toml
Labels: non-breaking, improvement

#414 Enable miplib datasets which was disabled and also update README
  benchmarks/README.md
  benchmarks/linear_programming/utils/get_datasets.py
Labels: non-breaking, improvement

#394 Add jump testing to nightly testing
  ci/test_wheel_cuopt.sh
  ci/thirdparty-testing/run_jump_tests.sh
Labels: non-breaking, improvement

#418 Compute relative gap with respect to user objectives
  cpp/src/dual_simplex/branch_and_bound.cpp
Labels: bug, non-breaking

#420 Fix linking errors in the test suite when disabling C adaptor
  cpp/tests/linear_programming/CMakeLists.txt
Labels: bug, non-breaking

#388 cuPDLPx
  benchmarks/linear_programming/cuopt/benchmark_helper.hpp
  benchmarks/linear_programming/cuopt/run_pdlp.cu
  cpp/cuopt_cli.cpp
  cpp/include/cuopt/linear_programming/constants.h
  cpp/include/cuopt/linear_programming/pdlp/pdlp_hyper_params.cuh
  cpp/include/cuopt/linear_programming/pdlp/solver_settings.hpp
  cpp/src/linear_programming/cusparse_view.cu
  cpp/src/linear_programming/cusparse_view.hpp
  cpp/src/linear_programming/initial_scaling_strategy/initial_scaling.cu
  cpp/src/linear_programming/initial_scaling_strategy/initial_scaling.cuh
  cpp/src/linear_programming/pdhg.cu
  cpp/src/linear_programming/pdhg.hpp
  cpp/src/linear_programming/pdlp.cu
  cpp/src/linear_programming/pdlp.cuh
  cpp/src/linear_programming/pdlp_constants.hpp
  cpp/src/linear_programming/pdlp_hyper_params.cu
  cpp/src/linear_programming/restart_strategy/localized_duality_gap_container.cu
  cpp/src/linear_programming/restart_strategy/pdlp_restart_strategy.cu
  cpp/src/linear_programming/restart_strategy/pdlp_restart_strategy.cuh
  cpp/src/linear_programming/solve.cu
  cpp/src/linear_programming/solve.cuh
  cpp/src/linear_programming/step_size_strategy/adaptive_step_size_strategy.cu
  cpp/src/linear_programming/step_size_strategy/adaptive_step_size_strategy.hpp
  cpp/src/linear_programming/termination_strategy/convergence_information.cu
  cpp/src/linear_programming/termination_strategy/convergence_information.hpp
  cpp/src/linear_programming/termination_strategy/termination_strategy.cu
  cpp/src/linear_programming/termination_strategy/termination_strategy.hpp
  cpp/src/linear_programming/utils.cuh
  cpp/src/math_optimization/solver_settings.cu
  cpp/src/mip/relaxed_lp/relaxed_lp.cu
  cpp/tests/linear_programming/pdlp_test.cu
  cpp/tests/linear_programming/unit_tests/solver_settings_test.cu
  cpp/tests/mip/unit_test.cu
  datasets/linear_programming/good-mps-free-ranges.mps
  docs/cuopt/source/cuopt-c/lp-milp/lp-milp-c-api.rst
  docs/cuopt/source/lp-milp-settings.rst
  python/cuopt/cuopt/linear_programming/solver/solver.pxd
  python/cuopt/cuopt/linear_programming/solver_settings/solver_settings.py
  python/cuopt/cuopt/tests/linear_programming/test_lp_solver.py
  python/cuopt_self_hosted/cuopt_sh_client/thin_client_solver_settings.py
  python/cuopt_server/cuopt_server/tests/test_pdlp_warmstart.py
  python/cuopt_server/cuopt_server/utils/linear_programming/data_definition.py
Labels: feature request, breaking, pdlp
