Repository NVIDIA/cuopt, pull requests merged in 2025-08, with the labels that each got.

#249 Fix a bug in basis repair. Recover from numerical issues in primal update.
  cpp/src/dual_simplex/basis_solves.cpp
  cpp/src/dual_simplex/phase2.cpp
  cpp/src/dual_simplex/right_looking_lu.cpp
Labels: bug, non-breaking

#254 Fix a segfault on bnatt500 due to small mu leading to inf/nan
  cpp/src/dual_simplex/basis_updates.cpp
Labels: bug, non-breaking

#267 Fix version in version tab, change log and fix typos
  docs/cuopt/source/project.json
  docs/cuopt/source/release-notes.rst
  docs/cuopt/source/versions1.json
Labels: doc, non-breaking

#287 Don't remove empty columns with infinite bounds
  cpp/src/dual_simplex/presolve.cpp
Labels: bug, non-breaking

#268 Adding actions to automate auto issue assignment and reminder on inactivity
  .github/workflows/inactivity_reminder.yaml
  .github/workflows/issue_automation.yaml
Labels: non-breaking, improvement

#258 FP as a local search
  benchmarks/linear_programming/cuopt/run_mip.cpp
  cpp/src/dual_simplex/branch_and_bound.cpp
  cpp/src/mip/diversity/diversity_manager.cu
  cpp/src/mip/diversity/diversity_manager.cuh
  cpp/src/mip/diversity/multi_armed_bandit.cuh
  cpp/src/mip/feasibility_jump/feasibility_jump.cu
  cpp/src/mip/feasibility_jump/feasibility_jump.cuh
  cpp/src/mip/local_search/feasibility_pump/feasibility_pump.cu
  cpp/src/mip/local_search/feasibility_pump/feasibility_pump.cuh
  cpp/src/mip/local_search/local_search.cu
  cpp/src/mip/local_search/local_search.cuh
  cpp/src/mip/problem/problem.cu
  cpp/src/mip/problem/problem.cuh
  cpp/src/mip/solve.cu
Labels: non-breaking, improvement

#335 Skip downloading netlib data
  benchmarks/linear_programming/utils/get_datasets.py
  cpp/tests/linear_programming/pdlp_test.cu
Labels: bug, non-breaking

#321 Container to work on all different users including root
  .github/workflows/test_images.yaml
  ci/docker/Dockerfile
  ci/docker/test_image.sh
Labels: non-breaking, improvement

#259 Sub-MIP recombiner and B&B global variable changes
  benchmarks/linear_programming/cuopt/mip_test_instances.hpp
  cpp/src/dual_simplex/basis_solves.cpp
  cpp/src/dual_simplex/branch_and_bound.cpp
  cpp/src/dual_simplex/branch_and_bound.hpp
  cpp/src/dual_simplex/pseudo_costs.cpp
  cpp/src/dual_simplex/pseudo_costs.hpp
  cpp/src/mip/diversity/diversity_config.hpp
  cpp/src/mip/diversity/diversity_manager.cu
  cpp/src/mip/diversity/diversity_manager.cuh
  cpp/src/mip/diversity/multi_armed_bandit.cuh
  cpp/src/mip/diversity/recombiners/recombiner_configs.hpp
  cpp/src/mip/diversity/recombiners/recombiner_stats.hpp
  cpp/src/mip/diversity/recombiners/sub_mip.cuh
  cpp/src/mip/local_search/local_search.cu
  cpp/src/mip/local_search/rounding/constraint_prop.cu
  cpp/src/mip/problem/presolve_data.cuh
  cpp/src/mip/problem/problem.cu
  cpp/src/mip/problem/problem.cuh
Labels: non-breaking, improvement

#269 Support cuda 12.9
  .github/workflows/build_test_publish_images.yaml
  .github/workflows/self_hosted_service_test.yaml
  CONTRIBUTING.md
  README.md
  ci/build-service.Dockerfile
  ci/release/update-version.sh
  conda/environments/all_cuda-129_arch-aarch64.yaml
  conda/environments/all_cuda-129_arch-x86_64.yaml
  cpp/CMakeLists.txt
  dependencies.yaml
  docs/cuopt/source/cuopt-c/quick-start.rst
  docs/cuopt/source/cuopt-python/quick-start.rst
  docs/cuopt/source/cuopt-server/quick-start.rst
  docs/cuopt/source/system-requirements.rst
  helmchart/cuopt-server/values.yaml
Labels: non-breaking, improvement

#354 Enable singleton stuffing and use papilo default params
  cpp/src/mip/presolve/third_party_presolve.cpp
  cpp/tests/linear_programming/pdlp_test.cu
  cpp/tests/linear_programming/utilities/pdlp_test_utilities.cuh
Labels: non-breaking, improvement
